services:

  # =========================
  # PostgreSQL
  # =========================
  postgres:
    image: postgres:17-alpine

    container_name: devops-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  # =========================
  # Node.js API
  # =========================
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: devops-nodejs

    restart: unless-stopped

    environment:
      NODE_ENV: production
      PORT: 3000

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3000:3000"

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: